Fact Suggestions
SchweizerischeBundesbahnen/BCNFStar pull request #349
Opened 2022-07-25 11:39 UTC by janina-adamcic

Es gibt ein MethodObject names `PotentialFacts`, was für jede Tabelle im Star Schema berechnet ob sie "Faktenpotenzial" hat. Die Berechnung selbst ist aus einem Paper, muss nicht unbedingt nachvollzogen werden für Review.

Bei Tabellen die Faktenpotenzial haben ist jetzt im Star Modus ein Button, bei dem man bestätigen oder dementieren kann, ob die Tabelle tatsächlich eine Faktentabelle ist. Das läuft jeweils über zwei Commands. 

Das Schema merkt sich Tabellen die vom Nutzer als Fakt bestätigt oder dementiert wurden.

2022-07-25 14:32 UTC, 23mafi commented on frontend/src/app/components/graph/graph-element/graph-element.component.html
> +    style="left: 10px; top: 3px; background-color: green"
eigentlich verwenden wir keine Style Attribute, bitte in Klasse auslagern

2022-07-25 15:45 UTC, 23mafi requested changes
die Styles sollten zu classes werden

Soll sowas auch in die Marie Persisiterung mit übernommen? Falls ja könnte man das noch ergänzen.

2022-07-25 15:45 UTC, 23mafi commented on frontend/src/app/components/graph/graph-element/graph-element.component.html
> +  <div style="display: flex; justify-content: space-evenly">
s.o.

2022-07-26 11:57 UTC, t-straeubig approved these changes
bitte noch die weitergabe der suggested "Eigenschaft" an durch split und join etc. entstehende Tabellen gewährleisten.

2022-07-26 12:14 UTC, t-straeubig approved these changes

2022-07-26 16:59 UTC, 23mafi approved these changes

2022-07-27 08:45 UTC, merged